#!/bin/bash
#displays your current Global IP

key="$HOME/bin/index.html"

if [ $# -eq 0 ]; then
        if [ -f $HOME/bin/index.html ]; then
                rm $HOME/bin/index.html
        fi

        `wget -q -P $HOME/bin/ "www.ipchicken.com"`
else
        echo "usage: ./myip.sh"
        exit 1
fi

cat $key | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" | head -1

