#!/bin/bash
#displays your current Global IP

key="index.html"

if [ $# -eq 0 ]; then
        if [ -f index.html ]; then
                rm index.html
        fi

        `wget -q "www.ipchicken.com"`
else
        echo "usage: ./myip.sh"
        exit 1
fi

cat $key | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" | head -1

